export interface Category {
  id: string;
  label: string;
  checked?: boolean;
}

export const mockCategories: Category[] = [
  { id: 'benefits', label: 'Benefits' },
  { id: 'payroll', label: 'Payroll' },
  { id: 'human-resources', label: 'Human Resources' },
  { id: 'wellness-programs', label: 'Wellness Programs' },
  { id: 'training-and-development', label: 'Training & Development' },
  { id: 'company-policies', label: 'Company Policies' },
  { id: 'retirement-plans', label: 'Retirement Plans' },
  { id: 'insurance', label: 'Insurance' },
  { id: 'employee-relations', label: 'Employee Relations' },
  { id: 'workplace-safety', label: 'Workplace Safety' },
  { id: 'diversity-and-inclusion', label: 'Diversity & Inclusion' },
  { id: 'recruitment', label: 'Recruitment' },
  { id: 'performance-management', label: 'Performance Management' },
  { id: 'compensation', label: 'Compensation' },
  { id: 'compliance', label: 'Compliance' },
  { id: 'employee-engagement', label: 'Employee Engagement' },
  { id: 'time-off-and-leaves', label: 'Time Off & Leaves' },
  { id: 'remote-work-policies', label: 'Remote Work Policies' },
  { id: 'health-and-safety', label: 'Health & Safety' },
  { id: 'legal-and-compliance', label: 'Legal & Compliance' },
  { id: 'career-growth', label: 'Career Growth' },
  { id: 'onboarding', label: 'Onboarding' },
  { id: 'exit-process', label: 'Exit Process' },
  { id: 'corporate-culture', label: 'Corporate Culture' },
  { id: 'salaries-and-wages', label: 'Salaries & Wages' },
  { id: 'internship-programs', label: 'Internship Programs' },
  { id: 'work-life-balance', label: 'Work-Life Balance' },
  { id: 'leadership-training', label: 'Leadership Training' },
  { id: 'conflict-resolution', label: 'Conflict Resolution' },
  { id: 'ethics-and-conduct', label: 'Ethics & Conduct' },
  { id: 'employee-assistance-programs', label: 'Employee Assistance Programs' },
  { id: 'professional-development', label: 'Professional Development' },
  { id: 'sick-leave-policies', label: 'Sick Leave Policies' },
  { id: 'vacation-policies', label: 'Vacation Policies' },
  { id: 'employee-feedback', label: 'Employee Feedback' },
  { id: 'hybrid-work-guidelines', label: 'Hybrid Work Guidelines' },
  { id: 'equal-employment-opportunity', label: 'Equal Employment Opportunity' },
  { id: 'labor-laws', label: 'Labor Laws' },
  { id: 'mental-health-support', label: 'Mental Health Support' },
  { id: 'sustainability-in-workplace', label: 'Sustainability in Workplace' },
  { id: 'team-building-activities', label: 'Team Building Activities' },
  { id: 'parental-leave', label: 'Parental Leave' },
  { id: 'disability-support', label: 'Disability Support' },
  { id: 'union-relations', label: 'Union Relations' },
  { id: 'dress-code', label: 'Dress Code' },
  { id: 'office-perks', label: 'Office Perks' },
  { id: 'it-policies', label: 'IT Policies' },
  { id: 'job-descriptions', label: 'Job Descriptions' },
  { id: 'hiring-process', label: 'Hiring Process' },
  { id: 'promotion-criteria', label: 'Promotion Criteria' },
  { id: 'hr-technology', label: 'HR Technology' },
  { id: 'annual-reviews', label: 'Annual Reviews' },
  { id: 'flexible-working-hours', label: 'Flexible Working Hours' },
  { id: 'health-benefits', label: 'Health Benefits' },
  { id: 'educational-assistance', label: 'Educational Assistance' },
  { id: 'performance-bonuses', label: 'Performance Bonuses' },
  { id: 'termination-policies', label: 'Termination Policies' },
  { id: 'whistleblower-policies', label: 'Whistleblower Policies' },
  { id: 'ethical-standards', label: 'Ethical Standards' },
  { id: 'cybersecurity-policies', label: 'Cybersecurity Policies' },
  { id: 'social-media-guidelines', label: 'Social Media Guidelines' },
  { id: 'office-relocation', label: 'Office Relocation' },
  { id: 'diversity-training', label: 'Diversity Training' },
  { id: 'wellness-stipends', label: 'Wellness Stipends' },
  { id: 'pension-plans', label: 'Pension Plans' },
  { id: 'career-pathways', label: 'Career Pathways' },
  { id: 'hr-analytics', label: 'HR Analytics' },
  { id: 'training-policies', label: 'Training Policies' },
  { id: 'holiday-allowance', label: 'Holiday Allowance' },
  { id: '401k-contributions', label: '401(k) Contributions' },
  { id: 'stock-options', label: 'Stock Options' },
  { id: 'team-retreats', label: 'Team Retreats' },
  { id: 'professional-ethics', label: 'Professional Ethics' },
  { id: 'leadership-development', label: 'Leadership Development' },
  { id: 'workplace-rights', label: 'Workplace Rights' },
  { id: 'freelance-and-contractor-guidelines', label: 'Freelance & Contractor Guidelines' },
  { id: 'hr-compliance-reports', label: 'HR Compliance Reports' },
  { id: 'employee-records', label: 'Employee Records' },
  { id: 'sabbatical-policies', label: 'Sabbatical Policies' },
  { id: 'recognition-programs', label: 'Recognition Programs' },
  { id: 'employee-discounts', label: 'Employee Discounts' },
  { id: 'company-holidays', label: 'Company Holidays' },
  { id: 'disciplinary-actions', label: 'Disciplinary Actions' },
  { id: 'hr-automation', label: 'HR Automation' },
  { id: 'health-screening-programs', label: 'Health Screening Programs' },
  { id: 'data-privacy-policies', label: 'Data Privacy Policies' },
  { id: 'hr-chatbots', label: 'HR Chatbots' },
  { id: 'office-ergonomics', label: 'Office Ergonomics' },
  { id: 'compensation-planning', label: 'Compensation Planning' },
  { id: 'remote-work-stipends', label: 'Remote Work Stipends' },
  { id: 'workplace-surveys', label: 'Workplace Surveys' },
  { id: 'conflict-management', label: 'Conflict Management' },
  { id: 'performance-metrics', label: 'Performance Metrics' },
  { id: 'pay-equity', label: 'Pay Equity' },
  { id: 'employment-contracts', label: 'Employment Contracts' },
  { id: 'consultant-hiring', label: 'Consultant Hiring' },
  { id: 'sick-pay', label: 'Sick Pay' },
  { id: 'ethics-hotlines', label: 'Ethics Hotlines' },
  { id: 'career-counseling', label: 'Career Counseling' },
  { id: 'visa-sponsorship', label: 'Visa Sponsorship' },
  { id: 'cultural-sensitivity-training', label: 'Cultural Sensitivity Training' }
];

